---
server:
  port: 8099
  contextPath: /statistics
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/statitstics
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

